import defaultImage from '../CategoryCards/Assets/default.png'
import wiresImage from '../CategoryCards/Assets/wires.jpg'
import plumbingImage from '../CategoryCards/Assets/Plumbing.jpg'
import paintingImage from '../CategoryCards/Assets/painting.jpg'
import testImage from '../CategoryCards/Assets/test.png'
import testImage2 from '../CategoryCards/Assets/test2.png'
import lightImage from '../CategoryCards/Assets/light.jpg'
import lampImage from '../CategoryCards/Assets/lamp.png'

export const CategoriesData = [
	{
		id: 1,
		name: 'Elec sub',
		img: defaultImage,
		new: false,
		title: 'title',
		metaDescription: 'description ',
		metaSlug: 'slug',
		language: 'English',
		parent: 'Electrical',
	},
	{
		id: 2,
		name: 'Wires',
		img: wiresImage,
		new: false,
		title: 'title',
		metaDescription: 'description ',
		metaSlug: 'slug',
		language: 'English',
		parent: 'Electrical',
	},
	{
		id: 3,
		name: 'Painting',
		img: paintingImage,
		new: false,
		title: 'title',
		metaDescription: 'description ',
		metaSlug: 'slug',
		language: 'English',
		parent: 'Electrical',
	},
	{
		id: 4,
		name: 'Electrical',
		img: wiresImage,
		new: false,
		title: 'title',
		metaDescription: 'description ',
		metaSlug: 'slug',
		language: 'English',
		parent: 'Electrical',
	},
	{
		id: 5,
		name: 'مواسير صرف',
		img: defaultImage,
		new: false,
		title: 'title',
		metaDescription: 'description ',
		metaSlug: 'slug',
		language: 'English',
		parent: 'Electrical',
	},
	{
		id: 6,
		name: 'Plumbing',
		img: plumbingImage,
		new: false,
		title: 'title',
		metaDescription: 'description ',
		metaSlug: 'slug',
		language: 'English',
		parent: 'Electrical',
	},
	{
		id: 7,
		name: 'test sub category',
		img: testImage,
		new: false,
		title: 'title',
		metaDescription: 'description ',
		metaSlug: 'slug',
		language: 'English',
		parent: 'Electrical',
	},
	{
		id: 8,
		name: 'test category',
		img: testImage2,
		new: false,
		title: 'title',
		metaDescription: 'description ',
		metaSlug: 'slug',
		language: 'English',
		parent: 'Electrical',
	},
	{
		id: 9,
		name: 'Lighting',
		img: lightImage,
		new: true,
		title: 'title',
		metaDescription: 'description ',
		metaSlug: 'slug',
		language: 'English',
		parent: 'Electrical',
	},
	{
		id: 10,
		name: 'Electrical',
		img: lampImage,
		new: true,
		title: 'title',
		metaDescription: 'description ',
		metaSlug: 'slug',
		language: 'English',
		parent: 'Electrical',
	},
]
