export const VendorData = [
	{
		id: 1,
		name: 'Name 1',
		title: 'Title1',
		phone: '0123456789',
		address: 'address',
		metaDescription: 'description ',
		metaSlug: 'slug',
	},
	{
		id: 2,
		name: 'Name 2',
		title: 'Title2',
		phone: '0123456789',
		address: 'address',
		metaDescription: 'description ',
		metaSlug: 'slug',
	},
	{
		id: 3,
		name: 'Name 3',
		title: 'Title3',
		phone: '0123456789',
		address: 'address',
		metaDescription: 'description ',
		metaSlug: 'slug',
	},
	{
		id: 4,
		name: 'Name 4',
		title: 'Title4',
		phone: '0123456789',
		address: 'address',
		metaDescription: 'description ',
		metaSlug: 'slug',
	},
	{
		id: 5,
		name: 'Name 5',
		title: 'Title5',
		phone: '0123456789',
		address: 'address',
		metaDescription: 'description ',
		metaSlug: 'slug',
	},
	{
		id: 6,
		name: 'Name 6',
		title: 'Title6',
		phone: '0123456789',
		address: 'address',
		metaDescription: 'description ',
		metaSlug: 'slug',
	},
	{
		id: 7,
		name: 'Name 7',
		title: 'Title7',
		phone: '0123456789',
		address: 'address',
		metaDescription: 'description ',
		metaSlug: 'slug',
	},
]
